Add delay in client update to account for clock drift  (#1477)
* Adjust the client state clock drift on creation

* Add check for clock drift and resonably delay the client update if
needed.

* Add max_block_time in config

* Pass dst config to build_client_state.

* Update comments

* Comments, unwraps,

* Minor renaming ChainStatus -> StatusResponse

* Fixed default config.toml

* max_clock_drift(); removed mut from config() param

* Whitespace nits

* Refactor client state drift calculation for CosmosSDK chain endpoint

* post-merge fixes

* Bumped rust version in readmes.

The reason is that tonic doesn't compile on pre 1.56, with error below:
cargo build
error: failed to download `tonic v0.6.1`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/adizere/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.6.1/Cargo.toml`

Caused by:
  feature `edition2021` is required

  The package requires the Cargo feature called `edition2021`, but that feature is not stabilized in this version of Cargo (1.55.0 (32da73ab1 2021-08-23)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2021 for more information about the status of this feature.

* Fix todo

* changelog

Co-authored-by: Adi Seredinschi <adi@informal.systems>